<?php

?>

<!-- Notification area -->
<div class="row">
    <div class="col-lg-3 col-xs-6">
      	<div class="small-box bg-aqua">
        	<div class="inner">
          		<h3><?php echo (isset($this->dailyLoans)? $this->dailyLoans : 'error')?></h3>
				<p>Adelantos Pendientes</p>
            </div>
            
            <div class="icon">
            	<i class="fa fa-money"></i>
            </div>
            <a href="#" class="small-box-footer">Ver detalle <i class="fa fa-arrow-circle-right"></i></a>
      	</div>
    </div>
        
    <div class="col-lg-3 col-xs-6">
      	<div class="small-box bg-green">
            <div class="inner">
          		<h3><?php echo (isset($this->severance)? $this->severance : 'error')?></h3>
				<p>Liquidaciones</p>
            </div>
            
            <div class="icon">
            	<i class="ion ion-person-add"></i>
            </div>
            <a href="#" class="small-box-footer">Ver detalle <i class="fa fa-arrow-circle-right"></i></a>
      	</div>
    </div>

    <div class="col-lg-3 col-xs-6">
      	<div class="small-box bg-yellow">
        	<div class="inner">
            	<h3><?php echo (isset($this->oilChanges)? $this->oilChanges : 'error')?></h3>
				<p>Cambios de Aceite</p>
            </div>
            
            <div class="icon">
          		<i class="fa fa-truck"></i>
            </div>
            <a href="#" class="small-box-footer">Ver detalle <i class="fa fa-arrow-circle-right"></i></a>
      	</div>
    </div>
        
    <div class="col-lg-3 col-xs-6">
      	<div class="small-box bg-red">
           	<div class="inner">
            	<h3><?php echo (isset($this->unattendedClients)? $this->unattendedClients : 'error')?></h3>
            	<p>Clientes por atender</p>
            </div>
            
            <div class="icon">
            	<i class="fa fa-book"></i>
            </div>
            <a href="#" class="small-box-footer">Ver detalle  <i class="fa fa-arrow-circle-right"></i></a>
      	</div>
    </div>

</div>
      
<div class="row">
    <section class="col-lg-7 connectedSortable">

          <!-- TO DO List -->
  		<div class="box box-primary">
            <div class="box-header">
              	<i class="ion ion-clipboard"></i>
				<h3 class="box-title">Tareas pendientes</h3>

		       	<div class="box-tools pull-right">
		            <ul class="pagination pagination-sm inline">
		              	<li><a href="#">&laquo;</a></li>
		              	<li><a href="#">1</a></li>
		              	<li><a href="#">2</a></li>
		              	<li><a href="#">3</a></li>
		              	<li><a href="#">&raquo;</a></li>
		            </ul>
		       	</div>
	        </div>
            
            <div class="box-body">
              	<ul class="todo-list">
                	<li>
                      	<span class="handle">
                    		<i class="fa fa-ellipsis-v"></i>
                        	<i class="fa fa-ellipsis-v"></i>
                      	</span>
                  
                  		<input type="checkbox" value="" name="">
                  
                  		<span class="text">Design a nice theme</span>
                  
                  		<small class="label label-danger"><i class="fa fa-clock-o"></i> 2 mins</small>
                  
                  		<div class="tools">
                    		<i class="fa fa-edit"></i>
                    		<i class="fa fa-trash-o"></i>
                  		</div>
                	</li>
                	
                	<li>
                      	<span class="handle">
                        	<i class="fa fa-ellipsis-v"></i>
                        	<i class="fa fa-ellipsis-v"></i>
                      	</span>
                  		<input type="checkbox" value="" name="">
                  		<span class="text">Make the theme responsive</span>
                  		<small class="label label-info"><i class="fa fa-clock-o"></i> 4 hours</small>
                  		<div class="tools">
                    		<i class="fa fa-edit"></i>
                    		<i class="fa fa-trash-o"></i>
                  		</div>
                	</li>
                	
                	<li>
                      	<span class="handle">
                        	<i class="fa fa-ellipsis-v"></i>
                        	<i class="fa fa-ellipsis-v"></i>
                      	</span>
                  		<input type="checkbox" value="" name="">
                  		<span class="text">Let theme shine like a star</span>
                  		<small class="label label-warning"><i class="fa fa-clock-o"></i> 1 day</small>
                  		<div class="tools">
                    		<i class="fa fa-edit"></i>
                    		<i class="fa fa-trash-o"></i>
                  		</div>
                	</li>
                	
                	<li>
                      	<span class="handle">
                        	<i class="fa fa-ellipsis-v"></i>
                        	<i class="fa fa-ellipsis-v"></i>
                      	</span>
                  		<input type="checkbox" value="" name="">
                  		<span class="text">Let theme shine like a star</span>
                  		<small class="label label-success"><i class="fa fa-clock-o"></i> 3 days</small>
                  		<div class="tools">
                    		<i class="fa fa-edit"></i>
                    		<i class="fa fa-trash-o"></i>
                  		</div>
                	</li>
                
                	<li>
                      	<span class="handle">
                        	<i class="fa fa-ellipsis-v"></i>
                        	<i class="fa fa-ellipsis-v"></i>
                      	</span>
                  		<input type="checkbox" value="" name="">
                  		<span class="text">Check your messages and notifications</span>
                  		<small class="label label-primary"><i class="fa fa-clock-o"></i> 1 week</small>
                  		<div class="tools">
                    		<i class="fa fa-edit"></i>
                    		<i class="fa fa-trash-o"></i>
              			</div>
                	</li>
                	
                	<li>
                      	<span class="handle">
                        	<i class="fa fa-ellipsis-v"></i>
                        	<i class="fa fa-ellipsis-v"></i>
                      	</span>
                  		<input type="checkbox" value="" name="">
                  		<span class="text">Let theme shine like a star</span>
                  		<small class="label label-default"><i class="fa fa-clock-o"></i> 1 month</small>
                  		<div class="tools">
                    		<i class="fa fa-edit"></i>
                    		<i class="fa fa-trash-o"></i>
                  		</div>
                	</li>
              	</ul>
            </div>
            
            <div class="box-footer clearfix no-border">
              	<button type="button" class="btn btn-default pull-right"><i class="fa fa-plus"></i> Agregar tarea</button>
            </div>
      	</div>      
    </section>
</div>
      