<?php
$this->headLink()
    ->appendStylesheet($this->constants->base_url . 'vendor/adminlte/plugins/dataTables/dataTables.bootstrap.css', 'all', true);

$this->inlineScript()
    ->appendFile($this->constants->base_url.'vendor/adminlte/plugins/dataTables/jquery.dataTables.js')
    ->appendFile($this->constants->base_url.'vendor/adminlte/plugins/dataTables/dataTables.bootstrap.js')
    ->appendFile($this->constants->base_url.'static/js/employees.js');

?>


<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <!-- .box-header -->
            <div class="box-header">
                <h3 class="box-title">Empleados</h3>                                    
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive">
                <div id="example2_wrapper" class="dataTables_wrapper form-inline" role="grid">
                    <table id="dataTable" class="table table-bordered table-hover dataTable">
                        <thead>
                            <tr role="row">
                                <th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Foto</th>
                                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Identificación</th>
                                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Nombre</th>
                                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Fecha Liquidacion</th>
                                <th class="sorting" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Acciones</th>
                            </tr>
                        </thead>
                    
                    </table>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
</div>