<div class="form-box" id="login-box">
    <div class="header">AdminSM</div>
    <form action="/login/validation/" method="post">
        <div class="body bg-gray">
            <div class="form-group">
                <input type="text" name="userid" class="form-control" placeholder="Usuario"/>
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="Contraseña"/>
            </div>          
        </div>
        <div class="footer">
            <button type="submit" class="btn bg-olive btn-block">Ingresar</button>  
        </div>
    </form>
</div>