<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><?php echo $this->title;?></title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.5 -->
  <link rel="stylesheet" href="vendor/bootstrap/assets/stylesheets/bootstrap.min.css">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="vendor/adminlte/css/AdminLTE.min.css">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="vendor/adminlte/css/skins/_all-skins.min.css">
  <!-- iCheck -->
  <link rel="stylesheet" href="vendor/adminlte/plugins/iCheck/flat/blue.css">
  <!-- Morris chart -->
  <link rel="stylesheet" href="vendor/adminlte/plugins/morris/morris.css">
  <!-- jvectormap -->
  <link rel="stylesheet" href="vendor/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
  <!-- Date Picker -->
  <link rel="stylesheet" href="vendor/adminlte/plugins/datepicker/datepicker3.css">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="vendor/adminlte/plugins/daterangepicker/daterangepicker-bs3.css">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="vendor/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="sidebar-mini wysihtml5-supported skin-green-light fixed" >
<div class="wrapper">
  	<header class="main-header">
	    <!-- Logo -->
	    <a href="/" class="logo">
	      	<span class="logo-lg"><b>Admin</b>SM</span>
	    </a>

	    <nav class="navbar navbar-static-top" role="navigation">
	      	<!-- Sidebar toggle button-->
	      	<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
	        	<span class="sr-only">Toggle navigation</span>
	      	</a>
	      	
		  	<!-- Navbar -->
		  	<div class="navbar-custom-menu">
		        <ul class="nav navbar-nav">
		          <!-- User Account nav menu -->
		          	<li class="dropdown user user-menu">
			            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
			              <span class="hidden-xs">Alexander Pierce</span>
			            </a>
			            <ul class="dropdown-menu">
			              	<!-- User image -->
			              	<li class="user-header">
			                	<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
				                <p>
				                  	Alexander Pierce - Web Developer
				                  	<small>Member since Nov. 2012</small>
				                </p>
			              	</li>
			              
			              	<!-- Menu Body -->
			              	<li class="user-body">
			                	<div class="row">
			                  		<div class="col-xs-4 text-center">
			                    		<a href="#">Followers</a>
			                  		</div>
		                  			
		                  			<div class="col-xs-4 text-center">
			                    		<a href="#">Sales</a>
			                  		</div>

			                  		<div class="col-xs-4 text-center">
			                    		<a href="#">Friends</a>
			                  		</div>
			                	</div>
			              	</li>
			              
		              		<!-- Menu Footer-->
			              	<li class="user-footer">
			                	<div class="pull-left">
			                  		<a href="#" class="btn btn-default btn-flat">Profile</a>
			                	</div>
			                	
			                	<div class="pull-right">
			                  		<a href="#" class="btn btn-default btn-flat">Sign out</a>
			                	</div>
			              	</li>
			            </ul>
		          	</li>
		        </ul>
	      	</div>
    	</nav>
  	</header>

	  <!-- sidebar -->
	  	<aside class="main-sidebar">
		    <section class="sidebar">
		      	<ul class="sidebar-menu">
		        	<li class="header">MAIN NAVIGATION</li>
		        
			        <li>
			          	<a href="/">
			            	<i class="fa fa-dashboard"></i> <span>Inicio</span>
			            	<small class="label pull-right bg-green">new</small>
			          	</a>
			        </li>

		        	<li>
		          		<a href="pages/calendar.html">
		            		<i class="fa fa-calendar"></i> <span>Calendario</span>
		            		<small class="label pull-right bg-red">3</small>
		          		</a>
		        	</li>

			        <li>
			          	<a href="pages/mailbox/mailbox.html">
			            	<i class="fa fa-envelope"></i> <span>Mailbox</span>
			            	<small class="label pull-right bg-yellow">12</small>
			          	</a>
			        </li>

			        <li class="treeview">
			          	<a href="#">
			            	<i class="fa fa-money"></i>
			            	<span>Planillas</span>
			            	<i class="fa fa-angle-left pull-right"></i>
			          	</a>
			          	<ul class="treeview-menu">
			            	<li><a href="#"><i class="fa fa-circle-o"></i> INS</a></li>
			            	<li><a href="#"><i class="fa fa-circle-o"></i> Semanal</a></li>
			            	<li><a href="#"><i class="fa fa-circle-o"></i> Prestamos</a></li>
			            	<li><a href="#"><i class="fa fa-circle-o"></i> Empleados</a></li>
			          	</ul>
			        </li>

			        <li class="treeview">
			          	<a href="#">
			            	<i class="fa fa-pie-chart"></i>
			            	<span>Reportes</span>
			            	<i class="fa fa-angle-left pull-right"></i>
			          	</a>
			          	<ul class="treeview-menu">
			            	<li><a href="#"><i class="fa fa-circle-o"></i> ChartJS</a></li>
			            	<li><a href="#"><i class="fa fa-circle-o"></i> Morris</a></li>
			            	<li><a href="#"><i class="fa fa-circle-o"></i> Flot</a></li>
			            	<li><a href="#"><i class="fa fa-circle-o"></i> Inline charts</a></li>
			          	</ul>
			        </li>
		      	</ul>
			</section>
	  	</aside>

	  	<!-- Content Wrapper. Contains page content -->
	  	<div class="content-wrapper">
	    
	    <!-- Content Header (Page header) -->
	    <section class="content-header">
	      	<h1>
	        	Dashboard
	        	<small>Control panel</small>
	      	</h1>
	      	<ol class="breadcrumb">
	        	<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
	        	<li class="active">Dashboard</li>
	      	</ol>
	    </section>

	    <!-- Main content -->
		<section class="content">
	    	<?php  echo $this->layout()->content ?>
		</section>
	</div>

	<footer class="main-footer">
	    <div class="pull-right hidden-xs">
	      	<b>AdminSM</b> Version 2.0.1
	      	<br/>
	    </div>
	</footer>
</div>
<!-- ./wrapper -->

<!-- jQuery 2.1.4 -->
<script src="vendor/adminlte/plugins/jQuery/jQuery-2.1.4.min.js"></script>
<!-- jQuery UI 1.11.4 -->
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.5 -->
<script src="vendor/bootstrap/assets/javascripts/bootstrap.min.js"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="vendor/adminlte/plugins/morris/morris.min.js"></script>
<!-- Sparkline -->
<script src="vendor/adminlte/plugins/sparkline/jquery.sparkline.min.js"></script>
<!-- jvectormap -->
<script src="vendor/adminlte/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="vendor/adminlte/plugins/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
<!-- jQuery Knob Chart -->
<script src="vendor/adminlte/plugins/knob/jquery.knob.js"></script>
<!-- daterangepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"></script>
<script src="vendor/adminlte/plugins/daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="vendor/adminlte/plugins/datepicker/bootstrap-datepicker.js"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="vendor/adminlte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js"></script>
<!-- Slimscroll -->
<script src="vendor/adminlte/plugins/slimScroll/jquery.slimscroll.min.js"></script>
<!-- FastClick -->
<script src="vendor/adminlte/plugins/fastclick/fastclick.js"></script>
<!-- AdminLTE App -->
<script src="vendor/adminlte/js/app.min.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="vendor/adminlte/js/pages/dashboard.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="vendor/adminlte/js/demo.js"></script>
</body>
</html>
